project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - about.qmd
    - hpcc.qmd
    - python_tutorials.qmd
    - r_tutorials.qmd
    - submission.qmd

website:
  title: "STAT COMP"
  navbar:
    background: primary
    right:
      - hpcc.qmd
      - text: "R"
        href: r_tutorials.qmd
      - text: "Python"
        href: python_tutorials.qmd
      - submission.qmd
      - text: "STAT GSA"
        href: https://ucrgradstat.github.io/
      - icon: github
        href: https://github.com/ucrgradstat/stat_comp
      

format:
  html:
    theme: cosmo
    css: styles.css

exclude: ["hpcc/*_cache"]
editor: visual

