---
title: "Submission"
description: |
  This website was built by graduate students to help each other learn about computing. Completing a graduate school is tough, and learning how to code or use certain software makes it even more tough. We hope these tutorials make it a bit easier on you to learn. This website contains a certain number of tutorials, but it will not contain everything. 

  Many graduate students have volunteered their time to create these tutorials. However, there may be a topic that we will not cover. Therefore, if you do learn something new that is not on the website, we encourage you to write a tutorial on how to do it. We would gladly host it on this website. Additionally, we will certainly give you credit for your work. Just follow the guidelines below and send us an email to ucr.grad.stat@gmail.com. With your help, this website will benefit everyone.

date: "`r Sys.Date()`"
site: distill::distill_website
---

## Guidelines

You are welcome to create the tutorial any way you want. Our only requirement is that the tutorial has an html file that we can use for the website. You may also submit an RMarkdown file and we will knit the document into an html file. 

If you choose to provide data for your tutorial, please make sure the that data is publicly available. We recommend that you simulate your own data to prevent any issues. Additionally, the smaller the data set, the better.

You may also submit a YouTube video for your tutorial. All you need to do is provide the link to your video.

Lastly, make sure you cite any code or work you use.

If you need any help, please feel free to email us at ucr.grad.stat@gmail.com.

## Removing A Tutorial

If you wish to no longer have your tutorial on this website, please email us and we will gladly remove it.




